<a href="https://colab.research.google.com/github/ArthurNSiqueira/tech_challenge/blob/main/Tech_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [159]:
import pandas as pd
import numpy as np

## Vinhos de Mesa

In [160]:
vinhos_de_mesa = pd.read_csv('/content/ImpVinhos (1).csv',sep = ';',thousands=".",decimal=",")
vinhos_de_mesa.head()

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
0,1,Africa do Sul,0,0.0,0,0,0,0,0,0,...,1092042,3604038,627150,1701072,859169,2508140,738116,2266827,522733,1732850
1,2,Alemanha,52297,30498.0,34606,26027,134438,92103,111523,98638,...,101055,412794,136992,504168,106541,546967,92600,438595,102456,557947
2,3,Argélia,0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Arábia Saudita,0,0.0,0,0,0,0,0,0,...,0,0,0,0,2510,8761,0,0,8,161
4,5,Argentina,19525,12260.0,24942,15022,104906,58137,116887,76121,...,16548931,54527380,22610267,66322932,26869241,79527959,27980574,87519642,25276991,83918138

In [161]:
# definindo o index como país para filtrar as colunas de 2008 a 2023
vinhos_de_mesa = vinhos_de_mesa.set_index('País')

In [162]:
# filtrando as colunas de 2008 a 2023 para as analises
colunas_15anos = vinhos_de_mesa.columns[-32:]
vinhos_de_mesa = vinhos_de_mesa[colunas_15anos]

### Valor Vinho de mesa

In [163]:
# Pegando apenas as colunas impares que são referentes ao valor importado
vinhos_de_mesa_valor = vinhos_de_mesa.iloc[:,1::2]
vinhos_de_mesa_valor

,2008.1,2009.1,2010.1,2011.1,2012.1,2013.1,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
País,,,,,,,,,,,,,,,,
Africa do Sul,1151699,1931449,3600658,2136394,3041449,1985184,3033932,2996543,1686226,3241298,3574371,3604038,1701072,2508140,2266827,1732850
Alemanha,1063825,291876,784674,933545,591167,414070,483316,358275,606333,315959,516975,412794,504168,546967,438595,557947
Argélia,0,0,0,0,0,0,0,0,43,0,0,0,0,0,0,0
Arábia Saudita,0,0,0,0,0,0,0,0,43,0,3249,0,0,8761,0,161
Argentina,37382581,38521731,52126581,58806736,55633562,49524694,53815956,48043201,45214862,51770842,52817642,54527380,66322932,79527959,87519642,83918138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ucrânia,0,0,0,0,0,0,0,0,9679,931,0,3074,0,0,0,0
Uruguai,2089539,1953390,3175051,3481552,3735892,3740613,3782282,4069100,5099162,7751966,8467846,7938059,10146829,10063341,9867675,9276001
Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não declarados,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Outros,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [164]:
# corringindo o nome das colunas
vinhos_de_mesa_valor.columns = vinhos_de_mesa_valor.columns.str[:-2]

In [165]:
#criando uma coluna com o total de valor importado de vinhos de mesa
vinhos_de_mesa_valor['Total'] = vinhos_de_mesa_valor.sum(axis = 1)
# ordenando o total importado de vinho de mesa do maior para o menor
vinhos_de_mesa_valor = vinhos_de_mesa_valor.sort_values(by = 'Total',ascending = False)

<ipython-input-165-8e1277d2c1a9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vinhos_de_mesa_valor['Total'] = vinhos_de_mesa_valor.sum(axis = 1)

In [166]:
# ordenando o total importado de vinho de mesa do maior para o menor
vinhos_de_mesa_valor = vinhos_de_mesa_valor.sort_values(by = 'Total',ascending = False)

In [167]:
# Criando uma coluna com o percentual
total_vendas = vinhos_de_mesa_valor['Total'].sum()
vinhos_de_mesa_valor['percentual'] = (vinhos_de_mesa_valor['Total'] / total_vendas) * 100
vinhos_de_mesa_valor['percentual'] = vinhos_de_mesa_valor['percentual'].round(5)

In [168]:
# voltando o com uma coluna de indice
vinhos_de_mesa_valor = vinhos_de_mesa_valor.reset_index()

In [171]:
# exportando para o csv
vinhos_de_mesa_valor.to_csv('Valor Importado Vinho de Mesa.csv')

### Vinho de Mesa Quantidade

In [53]:
# separando as colunas com a quantidade de vinho de mesa importada
vinhos_de_mesa_quantidade = vinhos_de_mesa.iloc[:,0::2]
vinhos_de_mesa_quantidade

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Africa do Sul,315380,493093,966276,507509,722327,475331,722715,743335,578829,1138732,1127053,1092042,627150,859169,738116,522733
Alemanha,293935,56075,192661,198025,113243,114866,115804,95171,158386,83289,142971,101055,136992,106541,92600,102456
Argélia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Arábia Saudita,0,0,0,0,0,0,0,0,0,0,563,0,0,2510,0,8
Argentina,14417761,13902750,16965266,16673491,14613839,12732815,13437321,12465041,14098009,15461740,15221318,16548931,22610267,26869241,27980574,25276991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ucrânia,0,0,0,0,0,0,0,0,5319,865,0,4646,0,0,0,0
Uruguai,920389,750343,1219387,1264306,1323884,1372329,1237537,1399547,2215692,5009098,2836574,2778244,4079076,3788831,3394161,2905567
Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não declarados,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Outros,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [172]:
#criando uma coluna com o total da quantidade importado de vinhos de mesa
vinhos_de_mesa_quantidade['Total'] = vinhos_de_mesa_quantidade.sum(axis = 1)

<ipython-input-172-4fee14fa1f30>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vinhos_de_mesa_quantidade['Total'] = vinhos_de_mesa_quantidade.sum(axis = 1)

In [174]:
# ordenando o total importado de vinho de mesa do maior para o menor
vinhos_de_mesa_quantidade = vinhos_de_mesa_quantidade.sort_values(by = 'Total',ascending = False)

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Total
País,,,,,,,,,,,,,,,,,
Chile,18662626,22476643,26434744,26642889,30258795,28288212,35479279,36686870,43400991,51787643,51104825,52697108,72726186,69617587,68881232,62358765,697504395
Argentina,14417761,13902750,16965266,16673491,14613839,12732815,13437321,12465041,14098009,15461740,15221318,16548931,22610267,26869241,27980574,25276991,279275355
Portugal,6213781,5884719,7801759,8556375,9714940,9299080,9735153,9952290,10821232,17345709,17698831,18228699,23627260,25925363,24108787,25099409,230013387
Itália,9723292,8387908,11911190,12025827,10506144,8308831,8566756,8261383,7936409,11538990,10154564,10323254,9659999,11231625,9622119,8868133,157026424
Espanha,990697,1119540,1622100,1999970,2540209,2772104,2760797,3024533,3948614,7240535,5595268,5797980,7169384,8793911,6487047,6591628,68454317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Coreia do Sul, República",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Argélia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não declarados,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Outros,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [176]:
# Criando uma coluna com o percentual
quantidade_total = vinhos_de_mesa_quantidade['Total'].sum()
vinhos_de_mesa_quantidade['percentual'] = (vinhos_de_mesa_quantidade['Total'] / quantidade_total) * 100
vinhos_de_mesa_quantidade['percentual'] = vinhos_de_mesa_quantidade['percentual'].round(5)

In [178]:
# voltando o com uma coluna de indice
vinhos_de_mesa_quantidade = vinhos_de_mesa_quantidade.reset_index()

In [179]:
vinhos_de_mesa_quantidade

,País,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Total,percentual
0,Chile,18662626,22476643,26434744,26642889,30258795,28288212,35479279,36686870,43400991,51787643,51104825,52697108,72726186,69617587,68881232,62358765,697504395,44.46946
1,Argentina,14417761,13902750,16965266,16673491,14613839,12732815,13437321,12465041,14098009,15461740,15221318,16548931,22610267,26869241,27980574,25276991,279275355,17.80523
2,Portugal,6213781,5884719,7801759,8556375,9714940,9299080,9735153,9952290,10821232,17345709,17698831,18228699,23627260,25925363,24108787,25099409,230013387,14.66453
3,Itália,9723292,8387908,11911190,12025827,10506144,8308831,8566756,8261383,7936409,11538990,10154564,10323254,9659999,11231625,9622119,8868133,157026424,10.01123
4,Espanha,990697,1119540,1622100,1999970,2540209,2772104,2760797,3024533,3948614,7240535,5595268,5797980,7169384,8793911,6487047,6591628,68454317,4.36431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,"Coreia do Sul, República",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00000
64,Argélia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00000
65,Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00000
66,Não declarados,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00000
67,Outros,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00000

In [180]:
vinhos_de_mesa_quantidade.to_csv('Quantidade Importada de Vinho de Mesa.csv')

## Espumante

In [182]:
espumante = pd.read_csv('/content/ImpEspumantes (1).csv',sep=';')
espumante.head()

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
0,1,Africa do Sul,0,0,0,0,0,0,0,0,...,17583,72077,3574,14542,6980,36677,9882,64582,7650,69382
1,2,Alemanha,0,0,25,36,2864,2479,2900,3130,...,26853,169989,21174,65359,19977,46237,12447,26877,322,5111
2,3,Argentina,4980,3836,8811,7543,35301,26909,39208,20230,...,757716,2282614,469547,1304986,723847,2211657,1333420,4123623,839006,2765843
3,4,Austrália,0,0,0,0,0,0,0,0,...,16701,27592,7426,15190,8062,26208,0,0,3150,10474
4,5,Áustria,0,0,0,0,0,0,0,0,...,1269,11571,909,9399,90,1434,0,0,882,8833

In [188]:
# definindo o index como país para filtrar as colunas de 2008 a 2023
espumante = espumante.set_index('País')

In [191]:
# filtrando as colunas de 2008 a 2023 para as analises
colunas_15anos = espumante.columns[-32:]
espumante = espumante[colunas_15anos]

### Valor Espumante

In [192]:
# Pegando apenas as colunas impares que são referentes ao valor importado
espumante_valor = espumante.iloc[:,1::2]
espumante_valor

,2008.1,2009.1,2010.1,2011.1,2012.1,2013.1,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
País,,,,,,,,,,,,,,,,
Africa do Sul,30630,42463,37035,123099,133975,158325,114275,96316,50715,23919,74800,72077,14542,36677,64582,69382
Alemanha,12516,8434,5753,8800,9975,11745,34413,5589,8275,37116,82273,169989,65359,46237,26877,5111
Argentina,3094003,2730102,3583463,3818944,3985004,2545215,3221463,1814349,1240249,2249681,2462909,2282614,1304986,2211657,4123623,2765843
Austrália,3343,2108,0,174,0,419,0,15439,32115,51731,212199,27592,15190,26208,0,10474
Áustria,6680,0,0,0,1139,6050,6352,0,0,0,11638,11571,9399,1434,0,8833
Bermudas,0,0,0,0,0,0,0,0,0,0,0,0,0,611,67,54
Bahamas,0,0,0,0,0,0,0,684,688,11136,2283,0,0,0,0,0
Bélgica,0,0,0,0,0,0,0,0,0,50574,0,0,0,0,0,0
Brasil,7645,0,62570,52984,313190,44337,37228,47936,4936,180512,162992,238268,106310,3488,0,184
Bulgária,0,0,0,0,0,0,546,7,0,716,0,0,0,0,1535,0
Canada,0,0,0,0,0,0,0,0,0,0,109402,0,0,0,1017,279
Chile,234038,165731,243004,248691,484791,478646,599993,838250,523242,1350744,1312445,912613,775535,686466,959421,1952709
Croácia,0,0,0,0,0,0,0,483,0,0,0,0,0,0,0,0
Cuba,0,0,0,0,0,0,0,243,0,0,0,0,0,0,0,0
Emirados Árabes Unidos,0,0,0,0,0,0,271,2005,38954,0,0,0,0,0,0,0
Eslovênia,0,0,0,0,221,0,2329,5075,9486,10110,8860,2539,327,2426,2982,0
Espanha,1179471,1397582,1904476,3017324,4537094,3917939,4519845,4183324,3249876,5592839,5707839,4463736,3871128,5732174,5668798,9801916
Estados Unidos,34991,25952,49664,15458,88292,50841,101802,85864,30366,226792,64081,105197,31083,2173,2053,10273
França,10773247,11933677,17012302,20020633,22744192,22873679,20831149,21849752,12017375,14966946,12678962,13991734,8814571,12590570,13164535,20166147
Geórgia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2325,0
Granada,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40
Grécia,0,0,0,0,0,222,1459,1574,0,277,0,318,0,422,366,1757
Hong Kong,0,0,0,0,15170,1593,0,0,0,0,0,0,5061,0,0,0
Hungria,0,0,0,0,1317,2984,1715,0,5927,6960,5977,1379,2061,2471,3828,0
Indonésia,0,0,0,0,0,0,0,0,0,0,271,529,0,0,0,0
Irlanda,0,0,0,0,0,0,0,4062,0,0,0,0,0,0,0,0
Israel,6912,0,5467,11627,6552,0,0,0,0,0,0,17085,9540,0,0,0
Itália,4474690,2984665,4703738,4966429,4953550,4223637,4462987,3670403,3467993,5635842,5947967,4790173,3544718,3142129,3356633,3533749
Luxemburgo,0,0,0,0,1115,0,0,0,0,0,1902,4067,0,0,0,0
México,0,0,834,0,0,0,0,9334,0,0,777,1104,0,0,0,0
Moldávia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3713,1165
Nova Zelândia,3921,5106,6858,861,3046,1950,3023,1684,0,0,0,657,0,0,3114,0
Países Baixos,0,0,0,0,0,0,0,0,0,0,10695,47027,151690,0,0,0
Panamá,0,0,0,0,0,0,0,0,0,0,30546,0,0,0,0,0
Peru,0,0,0,0,0,0,977,0,0,0,0,0,0,0,0,0
Portugal,273717,164404,326868,317547,382541,331054,316889,223379,321629,492083,526987,621259,324099,277677,391952,386265
Reino Unido,0,0,0,0,0,0,0,4211,0,2424,104831,11869,17975,3016,0,28581
Romênia,0,0,0,0,0,0,1011,528,0,0,0,0,0,2271,5007,3841
Suíça,0,0,0,0,0,0,0,0,711,0,4031,0,15222,376,0,34430
Tunísia,0,0,0,2091,4035,3887,0,0,0,0,0,0,0,0,0,0
Ucrânia,0,0,0,0,0,0,0,0,2423,0,0,0,0,0,1616,0
Uruguai,8372,10200,19080,932,600,0,3310,2832,42863,7920,5786,22983,18124,47217,5579,45704
Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não declarados,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Outros,0,2665,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [193]:
# corringindo o nome das colunas
espumante_valor.columns = espumante_valor.columns.str[:-2]

In [195]:
#criando uma coluna com o total de valor importado do espumante
espumante_valor['Total'] = espumante_valor.sum(axis = 1)

<ipython-input-195-66c0d6ecc1a5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  espumante_valor['Total'] = espumante_valor.sum(axis = 1)

In [198]:
# ordenando o total importado do espumante do maior para o menor
espumante_valor = espumante_valor.sort_values(by = 'Total',ascending = False)

In [200]:
# Criando uma coluna com o percentual
total_vendas = espumante_valor['Total'].sum()
espumante_valor['percentual'] = (espumante_valor['Total'] / total_vendas) * 100
espumante_valor['percentual'] = espumante_valor['percentual'].round(5)

In [202]:
# voltando com uma coluna de indice
espumante_valor = espumante_valor.reset_index()

In [204]:
# exportando para o csv
espumante_valor.to_csv('Valor Importado Espumante.csv')

### Espumante Quantidade

In [206]:
# separando as colunas com a quantidade de vinho de mesa importada
espumante_quantidade = espumante.iloc[:,0::2]
espumante_quantidade.head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Africa do Sul,9212,10381,8121,20213,24954,26985,18659,19686,7394,4913,15368,17583,3574,6980,9882,7650
Alemanha,1959,1170,1116,810,1260,1247,5093,3647,3420,4819,18376,26853,21174,19977,12447,322
Argentina,1015357,894550,1086901,997492,963574,702963,807366,490536,358510,661857,706478,757716,469547,723847,1333420,839006
Austrália,495,225,0,45,0,30,0,4967,19182,19198,57917,16701,7426,8062,0,3150
Áustria,756,0,0,0,180,720,698,0,0,0,1228,1269,909,90,0,882

In [208]:
#criando uma coluna com o total da quantidade importado de espumante
espumante_quantidade['Total'] = espumante_quantidade.sum(axis = 1)

<ipython-input-208-4f4a0686e684>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  espumante_quantidade['Total'] = espumante_quantidade.sum(axis = 1)

In [210]:
# ordenando o total importado de espumante do maior para o menor
espumante_quantidade = espumante_quantidade.sort_values(by = 'Total',ascending = False)

In [212]:
# Criando uma coluna com o percentual
quantidade_total = espumante_quantidade['Total'].sum()
espumante_quantidade['percentual'] = (espumante_quantidade['Total'] / quantidade_total) * 100
espumante_quantidade['percentual'] = espumante_quantidade['percentual'].round(5)

In [214]:
# voltando o com uma coluna de indice
espumante_quantidade = espumante_quantidade.reset_index()

In [215]:
espumante_quantidade.head()

,País,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Total,percentual
0,França,991608,1130768,1462949,1802575,1852431,1491052,1230946,1341884,1171383,1778528,3637804,1610293,1116188,1134059,1268840,1401753,48846122,28.86841
1,Itália,1051675,693765,1079836,1137610,1123066,978230,1095148,1017420,1089617,3065767,2147490,1874314,1524542,1093108,1169909,952639,42188272,24.93357
2,Espanha,266955,388452,512539,831585,1054367,850428,925502,899587,864154,1493908,1515106,1440241,1421655,2016806,2236061,3438264,40311220,23.82422
3,Argentina,1015357,894550,1086901,997492,963574,702963,807366,490536,358510,661857,706478,757716,469547,723847,1333420,839006,25618240,15.14056
4,Chile,84673,39533,68562,66639,137790,123026,133935,236342,117678,304391,316293,233064,253225,232948,342625,592991,6567430,3.88140

In [216]:
espumante_quantidade.to_csv('Quantidade Importada de Espumante.csv')

## Uvas Frescas

In [217]:
uvas_frescas = pd.read_csv('/content/ImpFrescas.csv',sep=';')
uvas_frescas.head()

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
0,1,Argélia,0,0,0,0,0,0,0,0,...,0,0,21746,34476,0,0,0,0,0,0
1,2,Argentina,2412831,782408,1805310,684328,1965010,779841,396840,253061,...,3211513,4659791,1798220,2559671,1356735,1696659,771187,1053519,400781,525034
2,3,Brasil,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Chile,1557316,409704,1485897,381705,1680664,578569,2472710,958295,...,9082957,13450429,4943446,6986630,3888723,5404163,6536258,9640996,6144949,9738753
4,5,Colômbia,0,0,3312,2168,0,0,63645,37098,...,0,0,0,0,0,0,0,0,0,0

In [218]:
# definindo o index como país para filtrar as colunas de 2008 a 2023
uvas_frescas = uvas_frescas.set_index('País')
uvas_frescas.head()

,Id,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,1974,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
País,,,,,,,,,,,,,,,,,,,,,
Argélia,1,0,0,0,0,0,0,0,0,0,...,0,0,21746,34476,0,0,0,0,0,0
Argentina,2,2412831,782408,1805310,684328,1965010,779841,396840,253061,1179250,...,3211513,4659791,1798220,2559671,1356735,1696659,771187,1053519,400781,525034
Brasil,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Chile,4,1557316,409704,1485897,381705,1680664,578569,2472710,958295,2154407,...,9082957,13450429,4943446,6986630,3888723,5404163,6536258,9640996,6144949,9738753
Colômbia,5,0,0,3312,2168,0,0,63645,37098,131888,...,0,0,0,0,0,0,0,0,0,0

In [219]:
# filtrando as colunas de 2008 a 2023 para as analises
colunas_15anos = uvas_frescas.columns[-32:]
uvas_frescas = uvas_frescas[colunas_15anos]
uvas_frescas.head()

,2008,2008.1,2009,2009.1,2010,2010.1,2011,2011.1,2012,2012.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
País,,,,,,,,,,,,,,,,,,,,,
Argélia,0,0,0,0,0,0,0,0,0,0,...,0,0,21746,34476,0,0,0,0,0,0
Argentina,8941022,10223013,7453027,8062155,11559264,15926306,13438557,19759895,8714800,13595978,...,3211513,4659791,1798220,2559671,1356735,1696659,771187,1053519,400781,525034
Brasil,0,0,0,0,0,0,0,0,14612,37412,...,0,0,0,0,0,0,0,0,0,0
Chile,3479598,4246892,10846054,12828213,11806542,17019296,18620819,27472449,22385291,36393910,...,9082957,13450429,4943446,6986630,3888723,5404163,6536258,9640996,6144949,9738753
Colômbia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Uvas Frescas Valor

In [220]:
# Pegando apenas as colunas impares que são referentes ao valor importado
uvas_frescas_valor = uvas_frescas.iloc[:,1::2]
uvas_frescas_valor.head()

,2008.1,2009.1,2010.1,2011.1,2012.1,2013.1,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
País,,,,,,,,,,,,,,,,
Argélia,0,0,0,0,0,0,0,0,0,0,0,0,34476,0,0,0
Argentina,10223013,8062155,15926306,19759895,13595978,10558621,4852008,5636226,5771032,3302565,2499358,4659791,2559671,1696659,1053519,525034
Brasil,0,0,0,0,37412,0,0,0,0,0,0,0,0,0,0,0
Chile,4246892,12828213,17019296,27472449,36393910,43466944,47301298,36956724,30767570,29248621,25237521,13450429,6986630,5404163,9640996,9738753
Colômbia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [221]:
# corringindo o nome das colunas
uvas_frescas_valor.columns = uvas_frescas_valor.columns.str[:-2]

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Argélia,0,0,0,0,0,0,0,0,0,0,0,0,34476,0,0,0
Argentina,10223013,8062155,15926306,19759895,13595978,10558621,4852008,5636226,5771032,3302565,2499358,4659791,2559671,1696659,1053519,525034
Brasil,0,0,0,0,37412,0,0,0,0,0,0,0,0,0,0,0
Chile,4246892,12828213,17019296,27472449,36393910,43466944,47301298,36956724,30767570,29248621,25237521,13450429,6986630,5404163,9640996,9738753
Colômbia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [223]:
#criando uma coluna com o total de valor importado de uvas frescas
uvas_frescas_valor['Total'] = uvas_frescas_valor.sum(axis = 1)

<ipython-input-223-7b2b412661de>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uvas_frescas_valor['Total'] = uvas_frescas_valor.sum(axis = 1)

In [227]:
# ordenando o total importado de uvas frescas do maior para o menor
uvas_frescas_valor = uvas_frescas_valor.sort_values(by = 'Total',ascending = False)

In [228]:
# Criando uma coluna com o percentual
total_vendas = uvas_frescas_valor['Total'].sum()
uvas_frescas_valor['percentual'] = (uvas_frescas_valor['Total'] / total_vendas) * 100
uvas_frescas_valor['percentual'] = uvas_frescas_valor['percentual'].round(5)

In [230]:
# voltando o com uma coluna de indice
uvas_frescas_valor = uvas_frescas_valor.reset_index()

In [232]:
# exportando para o csv
uvas_frescas_valor.to_csv('Valor Importado Uvas Frescas.csv')

### Uvas Frescas Quantidade

In [234]:
# separando as colunas com a quantidade de uvas frescas importada
uvas_frescas_quantidade = uvas_frescas.iloc[:,0::2]
uvas_frescas_quantidade

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Argélia,0,0,0,0,0,0,0,0,0,0,0,0,21746,0,0,0
Argentina,8941022,7453027,11559264,13438557,8714800,5810559,2758211,3569873,3931377,2097970,1616855,3211513,1798220,1356735,771187,400781
Brasil,0,0,0,0,14612,0,0,0,0,0,0,0,0,0,0,0
Chile,3479598,10846054,11806542,18620819,22385291,24392313,25952434,24254096,18424582,18510455,16103415,9082957,4943446,3888723,6536258,6144949
Colômbia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Egito,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27760,0
Espanha,30350,124345,212463,993310,393387,246827,401281,145066,431567,243947,83212,51079,0,0,0,0
Estados Unidos,91055,120861,89492,3265,32458,80518,50811,16504,3522,2164,15100,1343,0,0,0,0
Grécia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Itália,0,14439,190141,552911,1154322,1073920,1228338,1053083,589675,788663,334544,591991,0,0,0,0
México,16656,31200,432639,233856,173184,298656,184747,133608,0,0,0,0,0,0,414622,0
Peru,0,75550,504154,240389,426468,728022,3184984,2645931,4399499,2553897,947045,1585923,487080,75768,0,1086032
Paraguai,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Portugal,6640,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Panamá,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Reino Unido,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Uruguai,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Venezuela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Não consta na tabela,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Outros,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [235]:
#criando uma coluna com o total da quantidade importado de vinhos de mesa
uvas_frescas_quantidade['Total'] = uvas_frescas_quantidade.sum(axis = 1)

<ipython-input-235-877c7e14ff25>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uvas_frescas_quantidade['Total'] = uvas_frescas_quantidade.sum(axis = 1)

In [236]:
# ordenando o total importado de uvas frescas do maior para o menor
uvas_frescas_quantidade = uvas_frescas_quantidade.sort_values(by = 'Total',ascending = False)

In [238]:
# Criando uma coluna com o percentual
quantidade_total = uvas_frescas_quantidade['Total'].sum()
uvas_frescas_quantidade['percentual'] = (uvas_frescas_quantidade['Total'] / quantidade_total) * 100
uvas_frescas_quantidade['percentual'] = uvas_frescas_quantidade['percentual'].round(5)

In [239]:
# voltando o com uma coluna de indice
uvas_frescas_quantidade = uvas_frescas_quantidade.reset_index()

In [241]:
uvas_frescas_quantidade.to_csv('Quantidade Importada de Uvas Frescas.csv')

## Uvas Passas

In [243]:
uvas_passas = pd.read_csv('/content/ImpPassas.csv',sep=';')
uvas_passas.head()

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,40000,65452,0,0,0,484,0,0,0,0
1,2,África do Sul,0,0,0,0,0,0,0,0,...,270875,763921,616688,1433381,327000,531327,657826,1266633,151500,397825
2,3,"Alemanha, República Democrática",0,0,0,0,3000,3366,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Arábia Saudita,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Argentina,1530058,845068,1206326,936632,1047482,981648,1277380,1848195,...,24135143,48810789,24992502,36743996,24015825,33337604,20829418,35659325,19758017,36404746

In [244]:
# definindo o index como país para filtrar as colunas de 2008 a 2023
uvas_passas = uvas_passas.set_index('País')

In [245]:
# filtrando as colunas de 2008 a 2023 para as analises
colunas_15anos = uvas_passas.columns[-32:]
uvas_passas = uvas_passas[colunas_15anos]

### Valor Uvas Passas

In [246]:
# Pegando apenas as colunas impares que são referentes ao valor importado
uvas_passas_valor = uvas_passas.iloc[:,1::2]
uvas_passas_valor.head()

,2008.1,2009.1,2010.1,2011.1,2012.1,2013.1,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
País,,,,,,,,,,,,,,,,
Afeganistão,0,0,28050,669059,0,32600,789790,179545,0,0,0,65452,0,484,0,0
África do Sul,1032307,563360,2037012,596923,3527083,0,3507617,3278109,1487082,942442,3106052,763921,1433381,531327,1266633,397825
"Alemanha, República Democrática",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Arábia Saudita,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Argentina,26994373,24106889,34499504,43262321,43648893,47105230,34049473,32341307,34643821,34422405,43501396,48810789,36743996,33337604,35659325,36404746

In [247]:
# corringindo o nome das colunas
uvas_passas_valor.columns = uvas_passas_valor.columns.str[:-2]

In [248]:
#criando uma coluna com o total de valor importado de uvas passas
uvas_passas_valor['Total'] = uvas_passas_valor.sum(axis = 1)

<ipython-input-248-09edb7c31095>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uvas_passas_valor['Total'] = uvas_passas_valor.sum(axis = 1)

In [249]:
# ordenando o total importado de uvas passas do maior para o menor
uvas_passas_valor = uvas_passas_valor.sort_values(by = 'Total',ascending = False)

In [250]:
# Criando uma coluna com o percentual
total_vendas = uvas_passas_valor['Total'].sum()
uvas_passas_valor['percentual'] = (uvas_passas_valor['Total'] / total_vendas) * 100
uvas_passas_valor['percentual'] = uvas_passas_valor['percentual'].round(5)

In [251]:
# voltando o com uma coluna de indice
uvas_passas_valor = uvas_passas_valor.reset_index()

In [253]:
# exportando para o csv
uvas_passas_valor.to_csv('Valor Importado de Uvas Passas.csv')

### Uvas Passas Quantidades

In [254]:
# separando as colunas com a quantidade de uvas passas importada
uvas_passas_quantidade = uvas_passas.iloc[:,0::2]
uvas_passas_quantidade.head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Afeganistão,0,0,18000,400000,0,18000,456000,125000,0,0,0,40000,0,0,0,0
África do Sul,641051,195000,700846,184250,986750,0,2220275,1418063,617500,370500,1089700,270875,616688,327000,657826,151500
"Alemanha, República Democrática",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Arábia Saudita,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Argentina,15641645,17209323,17279688,20533473,19728826,20571302,14681136,20905602,23280908,19742996,23564519,24135143,24992502,24015825,20829418,19758017

In [255]:
#criando uma coluna com o total da quantidade importado de uvas passas
uvas_passas_quantidade['Total'] = uvas_passas_quantidade.sum(axis = 1)

<ipython-input-255-8642381988f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uvas_passas_quantidade['Total'] = uvas_passas_quantidade.sum(axis = 1)

In [256]:
# ordenando o total importado de uvas passas do maior para o menor
uvas_passas_quantidade = uvas_passas_quantidade.sort_values(by = 'Total',ascending = False)

In [257]:
# Criando uma coluna com o percentual
quantidade_total = uvas_passas_quantidade['Total'].sum()
uvas_passas_quantidade['percentual'] = (uvas_passas_quantidade['Total'] / quantidade_total) * 100
uvas_passas_quantidade['percentual'] = uvas_passas_quantidade['percentual'].round(5)

In [258]:
# voltando o com uma coluna de indice
uvas_passas_quantidade = uvas_passas_quantidade.reset_index()

In [259]:
uvas_passas_quantidade.to_csv('Quantidade Importada de Uvas Passas.csv')

## Suco de Uva

In [261]:
suco = pd.read_csv('/content/ImpSuco.csv',sep=';')
suco.head()

,Id,País,1970,1970.1,1971,1971.1,1972,1972.1,1973,1973.1,...,2019,2019.1,2020,2020.1,2021,2021.1,2022,2022.1,2023,2023.1
0,1,Africa do Sul,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Alemanha,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Argentina,0,0,0,0,0,0,3600,1350,...,0,0,0,0,0,0,0,0,0,0
3,4,Austria,0,0,0,0,0,0,0,0,...,666,655,0,0,0,0,0,0,0,0
4,5,Canadá,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [262]:
# definindo o index como país para filtrar as colunas de 2008 a 2023
suco = suco.set_index('País')

In [263]:
# filtrando as colunas de 2008 a 2023 para as analises
colunas_15anos = suco.columns[-32:]
suco = suco[colunas_15anos]

### Valor Suco de Uva

In [266]:
# Pegando apenas as colunas impares que são referentes ao valor importado
suco_valor = suco.iloc[:,1::2]
suco_valor.head()

,2008.1,2009.1,2010.1,2011.1,2012.1,2013.1,2014.1,2015.1,2016.1,2017.1,2018.1,2019.1,2020.1,2021.1,2022.1,2023.1
País,,,,,,,,,,,,,,,,
Africa do Sul,10961,9400,31729,34605,71839,68254,40489,13209,5841,17551,18334,0,0,0,0,0
Alemanha,68950,0,0,0,0,0,0,46692,75902,0,652,0,0,0,0,0
Argentina,0,0,138240,0,0,0,0,0,80898,90518,3139,0,0,0,0,0
Austria,0,0,0,3254,0,0,0,0,0,1467,0,655,0,0,0,0
Canadá,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [267]:
# corringindo o nome das colunas
suco_valor.columns = suco_valor.columns.str[:-2]

In [268]:
#criando uma coluna com o total de valor importado de suco de uva
suco_valor['Total'] = suco_valor.sum(axis = 1)

<ipython-input-268-321bc06a442c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  suco_valor['Total'] = suco_valor.sum(axis = 1)

In [269]:
# ordenando o total importado de uva passas do maior para o menor
suco_valor = suco_valor.sort_values(by = 'Total',ascending = False)

In [270]:
# Criando uma coluna com o percentual
total_vendas = suco_valor['Total'].sum()
suco_valor['percentual'] = (suco_valor['Total'] / total_vendas) * 100
suco_valor['percentual'] = suco_valor['percentual'].round(5)

In [271]:
# voltando o com uma coluna de indice
suco_valor = suco_valor.reset_index()

In [273]:
# exportando para o csv
suco_valor.to_csv('Valor Importado de Suco de Uva.csv')

### Suco de Uva Quantidade

In [274]:
# separando as colunas com a quantidade de suco de uva importada
suco_quantidade = suco.iloc[:,0::2]
suco_quantidade.head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
País,,,,,,,,,,,,,,,,
Africa do Sul,14379,11839,37353,38796,74388,67758,43104,13125,7154,22029,21618,0,0,0,0,0
Alemanha,60850,0,0,0,0,0,0,6496,6540,0,80,0,0,0,0,0
Argentina,0,0,108000,0,0,0,0,0,59028,72900,2998,0,0,0,0,0
Austria,0,0,0,3264,0,0,0,0,0,1333,0,666,0,0,0,0
Canadá,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [275]:
#criando uma coluna com o total da quantidade importado de suco de uva
suco_quantidade['Total'] = suco_quantidade.sum(axis = 1)

<ipython-input-275-bd3e182c47a8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  suco_quantidade['Total'] = suco_quantidade.sum(axis = 1)

In [276]:
# ordenando o total importado de vinho de mesa do maior para o menor
suco_quantidade = suco_quantidade.sort_values(by = 'Total',ascending = False)

In [277]:
# Criando uma coluna com o percentual
quantidade_total = suco_quantidade['Total'].sum()
suco_quantidade['percentual'] = (suco_quantidade['Total'] / quantidade_total) * 100
suco_quantidade['percentual'] = suco_quantidade['percentual'].round(5)

In [278]:
# voltando o com uma coluna de indice
suco_quantidade = suco_quantidade.reset_index()

In [280]:
suco_quantidade.to_csv('Quantidade Importada de Suco de Uva.csv')